bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student03
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student04
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student05
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student06
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student07
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student08
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student09
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student10
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student11
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student12
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student13
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student14
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student15
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student16
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student17
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student18
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student19
bash -x /Users/hugo/Dropbox/CloudStack/workshop/cloudmonkey_create_student.sh student20
